/**
 * Writes src/rules/titles.js from merc21/src: const.c's title_table (what
 * nanny and advance_level set a player's title to) and act_comm.c's
 * pose_table (do_pose). Generated, not retyped, like tools/gen-socials.mjs.
 *
 *     node tools/gen-titles.mjs
 *
 * The strings are read the way a C compiler reads them: adjacent literals
 * join, and an initializer longer than its array is cut to the array, so a
 * slip in the C source comes through here as it does in the mud.
 */
import { readFileSync, writeFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const MAX_CLASS = 4;
const MAX_LEVEL = 40;

/** The C string literals in `text`, adjacent ones joined, comma-separated. */
function literals(text) {
  const out = [];
  let joined = null;
  const token = /"((?:[^"\\]|\\.)*)"|(,)|(\/\*[\s\S]*?\*\/)/g;
  let m;
  while ((m = token.exec(text))) {
    if (m[3]) continue;
    if (m[2]) { if (joined !== null) out.push(joined); joined = null; continue; }
    joined = (joined || '') + m[1].replace(/\\"/g, '"');
  }
  if (joined !== null) out.push(joined);
  return out;
}

/** The text between the `{` after `marker` and its matching `}`. */
function initializer(src, marker) {
  const at = src.indexOf(marker);
  if (at < 0) throw new Error(`${marker} not found`);
  const open = src.indexOf('{', at);
  let depth = 0;
  for (let i = open; i < src.length; i++) {
    if (src[i] === '{') depth++;
    else if (src[i] === '}' && --depth === 0) return src.slice(open + 1, i);
  }
  throw new Error(`${marker}: unbalanced braces`);
}

const constC = readFileSync(join(root, 'merc21/src/const.c'), 'latin1');
const titles = literals(initializer(constC, 'title_table\t[MAX_CLASS][MAX_LEVEL+1][2]'));
if (titles.length !== MAX_CLASS * (MAX_LEVEL + 1) * 2) throw new Error(`const.c: ${titles.length} titles`);
const TITLES = [];
for (let c = 0; c < MAX_CLASS; c++) {
  TITLES.push([]);
  for (let l = 0; l <= MAX_LEVEL; l++) {
    const i = (c * (MAX_LEVEL + 1) + l) * 2;
    TITLES[c].push([titles[i], titles[i + 1]]);
  }
}

const commC = readFileSync(join(root, 'merc21/src/act_comm.c'), 'latin1');
const poseBody = initializer(commC, 'pose_table\t[]\t=');
// Each row is { { message[2*MAX_CLASS] } }: split on the rows' own braces.
const POSES = [];
for (const row of poseBody.split(/\}\s*\}\s*,?/).filter((r) => r.includes('"'))) {
  const strings = literals(row);
  POSES.push(strings.slice(0, 2 * MAX_CLASS));
}

const out = `/**
 * Generated by tools/gen-titles.mjs from merc21/src -- do not edit.
 *
 * TITLES[class][level][sex === 2 ? 1 : 0]: const.c's title_table, which
 * nanny and advance_level set as "the <title>".
 * POSES[row][2 * class + (0: to you, 1: to the room)]: act_comm.c's
 * pose_table, read as the compiler reads it (see the generator).
 */
export const TITLES = ${JSON.stringify(TITLES)};

export const POSES = ${JSON.stringify(POSES, null, 2)};
`;
writeFileSync(join(root, 'src/rules/titles.js'), out);
console.log(`${MAX_CLASS} x ${MAX_LEVEL + 1} titles and ${POSES.length} pose row(s) written to src/rules/titles.js`);
