/**
 * Writes src/rules/socials.js from merc21/src/interp.c's social_table, so the
 * table the command line uses is the mud's own text, not a retyping of it.
 *
 *     node tools/gen-socials.mjs
 */
import { readFileSync, writeFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const src = readFileSync(join(root, 'merc21/src/interp.c'), 'latin1');
const start = src.indexOf('social_table [] =');
if (start < 0) throw new Error('interp.c: social_table not found');
const body = src.slice(src.indexOf('{', start) + 1);
const entries = [];
const block = /\{\s*((?:(?:"(?:[^"\\]|\\.)*"|NULL)\s*,?\s*)+)\}/g;
let m;
while ((m = block.exec(body))) {
  const fields = [...m[1].matchAll(/"((?:[^"\\]|\\.)*)"|NULL/g)].map((f) => (f[0] === 'NULL' ? null : f[1].replace(/\\"/g, '"')));
  if (fields[0] === '') break;          // the terminator
  if (fields.length !== 8) throw new Error(`interp.c: social with ${fields.length} fields near ${JSON.stringify(fields[0])}`);
  entries.push(fields);
}
const out = `/**
 * interp.c: social_table, generated by tools/gen-socials.mjs -- do not edit.
 * Each row: name, char_no_arg, others_no_arg, char_found, others_found,
 * vict_found, char_auto, others_auto.
 */
export const SOCIALS = ${JSON.stringify(entries, null, 0).replace(/\],\[/g, '],\n  [').replace(/^\[\[/, '[\n  [').replace(/\]\]$/, '],\n]')};
`;
writeFileSync(join(root, 'src/rules/socials.js'), out);
console.log(`${entries.length} socials written to src/rules/socials.js`);
